version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: yomesumo_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
#      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mongo:
    image: mongo:latest
    container_name: yomesumo_mongo
    hostname: yomesumo_mongo
    ports:
      - "27021:27017"
    volumes:
      - ./dockerUtils/mongo_init.js:/docker-entrypoint-initdb.d/01-mongo-init.js:ro
      - yomesumo_mongo_db:/data/db
      - yomesumo_mongo_log:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: yomesumo-mensajes

volumes:
  db:
  pgadmin-data:
  yomesumo_mongo_db:
  yomesumo_mongo_log: